POST http://localhost:3001/api/quizes 
content-type: application/json

    {
      "question": "In which fast food chain can you order a Jamocha Shake?",
    "correct_answer": "Arby’s",
    "answers": [
      "McDonald’s",
      "Burger King",
      "Wendy’s",
      "Arby’s"]
  }